version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_POSTGRES_USERNAME}:${DB_POSTGRES_PASSWORD}@database:${DB_POSTGRES_PORT}/${DB_POSTGRES_DATABASE}
    ports:
      - 3000:3000
    depends_on:
      - database
    command: >
      sh -c "
        yarn prisma:migrate:deploy && node dist/server/main.js
      "
    volumes:
      - ./src/server/prisma:/usr/src/app/src/server/prisma:ro

  database:
    image: postgres
    container_name: checkbox-postgres
    environment:
      POSTGRES_DB: checkbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
